### PR TITLE
Move the LinkedIn API version to 2.0

### LINKED ISSUE #5953: LinkedIn authenticator Not Working for the newly created APIS.(only supports for version 1 APIs only.)
The existing LinkedIn authenticator only supports for version 1 APIs only [1]. It is mentioned in the documentation as well. But the issue is they have stopped supporting the LinkedIn API version 1 from 01.05.2019 [2]. 
Screenshot from 2019-07-19 18-50-23

So the existing connector won't support for the newly created LinkedIn APIs. 

If we are to support this we can modify the UI to add the API version and based on the API version we can change the URL value [3]. 

[1] https://github.com/wso2-extensions/identity-outbound-auth-linkedIn/blob/master/component/src/main/java/org/wso2/carbon/identity/authenticator/linkedIn/LinkedInAuthenticatorConstants.java#L25
[2] https://engineering.linkedin.com/blog/2018/12/developer-program-updates
[3] https://github.com/wso2-extensions/identity-outbound-auth-linkedIn/blob/master/component/src/main/java/org/wso2/carbon/identity/authenticator/linkedIn/LinkedInAuthenticator.java#L340

### PR DESCRIPTION
**Pull request by JKAUSHALYA**
Fix: https://github.com/wso2/product-is/issues/5953

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

**Review by denuwanthi — APPROVED** [review]

File: component/src/main/java/org/wso2/carbon/identity/authenticator/linkedIn/LinkedInAuthenticator.java [hunk 1]
```diff
@@ -381,35 +428,76 @@ public String getClaimDialectURI() {
...
+    public String getEmailEndpointURL(Map<String, String> authenticatorProperties) {
+
+        String emailEndpoint;
+        if (authenticatorProperties != null) {
+            emailEndpoint = authenticatorProperties.get(LinkedInAuthenticatorConstants.EMAIL_ENDPOINT);
+        } else {
+            emailEndpoint = LinkedInAuthenticatorConstants.LINKEDIN_EMAIL_ENDPOINT;
+        }
+
+        return emailEndpoint != null ? emailEndpoint : LinkedInAuthenticatorConstants.LINKEDIN_EMAIL_ENDPOINT;
```
Comment (Kanapriya) [inline component/src/main/java/org/wso2/carbon/identity/authenticator/linkedIn/LinkedInAuthenticator.java]: Shall we use StringUtils.isNotEmpty() for the null check

File: component/src/main/java/org/wso2/carbon/identity/authenticator/linkedIn/internal/LinkedInAuthenticatorServiceComponent.java [hunk 2]
```diff
@@ -39,24 +43,28 @@
...
      */
+    @Deactivate
     protected void deactivate(ComponentContext componentContext) {
+
         if (log.isDebugEnabled()) {
-            log.debug("linkedIn authenticator is deactivated");
+            log.debug("linkedIn authenticator is deactivated.");
         }
     }
 }
```
Comment (Kanapriya) [inline component/src/main/java/org/wso2/carbon/identity/authenticator/linkedIn/internal/LinkedInAuthenticatorServiceComponent.java]: Better to add a new line here

File: component/src/main/java/org/wso2/carbon/identity/authenticator/linkedIn/LinkedInAuthenticator.java [hunk 3]
```diff
@@ -123,23 +138,48 @@ private Boolean getLoginType(HttpServletRequest request) {
...
-        return LinkedInAuthenticatorConstants.LINKEDIN_OAUTH_ENDPOINT;
+
+        String authorizationEP;
+        if (authenticatorProperties != null) {
+            authorizationEP = authenticatorProperties.get(LinkedInAuthenticatorConstants.OAUTH2_AUTHZ_URL);
+        } else {
+            authorizationEP = LinkedInAuthenticatorConstants.LINKEDIN_OAUTH_ENDPOINT_V2;
+        }
+
+        return authorizationEP != null ? authorizationEP : LinkedInAuthenticatorConstants.LINKEDIN_OAUTH_ENDPOINT_V2;
```
Comment (Kanapriya) [inline component/src/main/java/org/wso2/carbon/identity/authenticator/linkedIn/LinkedInAuthenticator.java]: Better to use StringUtils.isNotEmpty() for null check

**Review by Kanapriya — APPROVED** [review]
